version: '3'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3333:3333"
    environment:
      - DATABASE_URL=postgres://cooperfilme-api:cooberfilmePass@db:5432/cooperfilme-db
    depends_on:
      - db

  db:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: cooperfilme-api
      POSTGRES_PASSWORD: cooberfilmePass
      POSTGRES_DB: cooperfilme-db
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata:
