version: '3'

services:  
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=cooperfilme-api
      - POSTGRES_PASSWORD=cooberfilmePass
      - POSTGRES_DB=cooperfilme-db
    container_name: cooperfilme-db
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3333
      - NEXTAUTH_LOGIN_URL=http://localhost:3333/auth/singin
      - NEXTAUTH_SECRET=secret
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3333:3333"
    environment:
      - DATABASE_URL=postgres://cooperfilme-api:cooberfilmePass@db:5432/cooperfilme-db
      - JWT_EXPIRATION_TIME=3600
      - JWT_SECRET_KEY=ashdlkasjhdklajslkd
      - PORT_APP = 3333
    depends_on:
      - db

volumes:
  dbdata:
